### ISSUE TITLE
Where is the actual theme file?

### ISSUE THREAD

**Issue by robrecord** [mbixby/blackbird#2]
looks like there's been a submodules mishap. I can't see the actual theme file anywhere - just a 'Blackbird' dir with all the resources. Any chance of readding?

Thanka for the great looking theme! :)

**Comment by andrebras** [comment]
try this:

```
git clone git@github.com:mbixby/blackbird.git --recursive
```

then check inside color-scheme folder

**Comment by mbixby** [comment]
The theme file is up, sorry for being late. I think it just changes the tabs and window background, nothing more.  I'll probably update it with changes from Bluebird when I'm less busy.
