### ISSUE TITLE
Whats the font used in last screenshot?

### ISSUE THREAD

**Issue by richellyitalo** [mbixby/blackbird#3]
Whats the font used in last screenshot?

**Comment by mbixby** [comment]
It's a customized version of Monaco that ships with macOS. Some glyphs are slightly different and there should be a bold variant.

See https://github.com/mbixby/bluebird/tree/master/font

https://en.wikipedia.org/wiki/Monaco_(typeface)

**Comment by richellyitalo** [comment]
Thanks. Works very well on Windows!
